COUNTRY_VARIANTS = {
    "Afghanistan": ["Islamic Republic of Afghanistan", "افغانستان", "Da Afġānistān Islāmī Jomhouriyet"],
    "Albania": ["Shqipëria", "Republic of Albania", "Republika e Shqipërisë"],
    "Algeria": ["الجزائر", "Al-Jazāʾir", "People's Democratic Republic of Algeria", "الجمهورية الجزائرية الديمقراطية الشعبية"],
    "Andorra": ["Principality of Andorra", "Principat d'Andorra"],
    "Angola": ["República de Angola", "Republic of Angola"],
    "Antigua and Barbuda": ["Antigua", "Wadadli"],
    "Argentina": ["Argentine Republic", "República Argentina", "United Provinces of the Río de la Plata", "Argentine Confederation"],
    "Armenia": ["Հայաստան", "Hayastan", "Republic of Armenia", "Հայաստանի Հանրապետություն"],
    "Australia": ["Commonwealth of Australia"],
    "Austria": ["Österreich", "Republic of Austria", "Republik Österreich"],
    "Azerbaijan": ["Azərbaycan", "Republic of Azerbaijan", "Azərbaycan Respublikası"],
    "Bahamas": ["The Bahamas", "Commonwealth of The Bahamas"],
    "Bahrain": ["البحرين", "Al-Bahrayn", "Kingdom of Bahrain", "مملكة البحرين"],
    "Bangladesh": ["বাংলাদেশ", "People's Republic of Bangladesh", "গণপ্রজাতন্ত্রী বাংলাদেশ"],
    "Barbados": [],
    "Belarus": ["Беларусь", "Republic of Belarus", "Рэспубліка Беларусь"],
    "Belgium": ["België", "Belgique", "Belgien", "Kingdom of Belgium", "Koninkrijk België", "Royaume de Belgique", "Königreich Belgien"],
    "Belize": ["British Honduras"],
    "Benin": ["République du Bénin", "Republic of Benin", "Dahomey"],
    "Bhutan": ["འབྲུག་ཡུལ", "Druk Yul", "Kingdom of Bhutan", "འབྲུག་རྒྱལ་ཁབ"],
    "Bolivia": ["Estado Plurinacional de Bolivia", "Plurinational State of Bolivia", "Buliwya", "Wuliwya", "Volívia"],
    "Bosnia and Herzegovina": ["Bosna i Hercegovina", "БиХ", "BiH"],
    "Botswana": ["Republic of Botswana", "Lefatshe la Botswana"],
    "Brazil": ["Brasil", "República Federativa do Brasil", "Federative Republic of Brazil"],
    "Brunei": ["Brunei Darussalam", "Nation of Brunei, Abode of Peace", "بروني دارالسلام"],
    "Bulgaria": ["България", "Republic of Bulgaria", "Република България"],
    "Burkina Faso": ["Burkina", "Land of Incorruptible People"],
    "Burundi": ["République du Burundi", "Republic of Burundi"],
    "Cambodia": ["កម្ពុជា", "Kampuchea", "Kingdom of Cambodia", "ព្រះរាជាណាចក្រកម្ពុជា"],
    "Cameroon": ["Cameroun", "République du Cameroun", "Republic of Cameroon"],
    "Canada": ["Dominion of Canada"],
    "Cape Verde": ["Cabo Verde", "República de Cabo Verde", "Republic of Cabo Verde"],
    "Central African Republic": ["République Centrafricaine", "Centrafrique", "Kôdörösêse tî Bêafrîka"],
    "Chad": ["تشاد", "Tchad", "République du Tchad", "Republic of Chad", "جمهورية تشاد"],
    "Chile": ["República de Chile", "Republic of Chile"],
    "China": ["中国", "Zhōngguó", "People's Republic of China", "中华人民共和国", "Zhōnghuá Rénmín Gònghéguó"],
    "Colombia": ["República de Colombia", "Republic of Colombia"],
    "Comoros": ["Comores", "Komori", "جزر القمر", "Union of the Comoros", "Union des Comores", "Udzima wa Komori", "الاتحاد القمري"],
    "Congo, Democratic Republic of the": ["DR Congo", "DRC", "DROC", "Congo-Kinshasa", "République Démocratique du Congo", "Democratic Republic of the Congo", "Congo Free State", "Belgian Congo", "Zaire"],
    "Congo, Republic of the": ["Congo", "Congo-Brazzaville", "République du Congo", "Republic of the Congo"],
    "Costa Rica": ["República de Costa Rica", "Republic of Costa Rica"],
    "Côte d'Ivoire": ["Ivory Coast", "République de Côte d'Ivoire", "Republic of Côte d'Ivoire"],
    "Croatia": ["Hrvatska", "Republic of Croatia", "Republika Hrvatska"],
    "Cyprus": ["Κύπρος", "Kıbrıs", "Kypros", "Republic of Cyprus", "Κυπριακή Δημοκρατία", "Kıbrıs Cumhuriyeti"],
    "Czech Republic": ["Czechia", "Česko", "Česká republika", "České země"],
    "Denmark": ["Danmark", "Kingdom of Denmark", "Kongeriget Danmark"],
    "Djibouti": ["جيبوتي", "Jībūtī", "Republic of Djibouti", "République de Djibouti", "جمهورية جيبوتي", "Gabuutih Ummuuno"],
    "Dominica": ["Commonwealth of Dominica", "Dominique", "Wai'tu kubuli"],
    "Dominican Republic": ["República Dominicana", "La Dominicana"],
    "Ecuador": ["República del Ecuador", "Republic of Ecuador"],
    "Egypt": ["مصر", "Misr", "Arab Republic of Egypt", "جمهورية مصر العربية"],
    "El Salvador": ["República de El Salvador", "Republic of El Salvador"],
    "Equatorial Guinea": ["Guinea Ecuatorial", "Guinée équatoriale", "República da Guiné Equatorial", "Republic of Equatorial Guinea"],
    "Eritrea": ["إرتريا", "ኤርትራ", "State of Eritrea", "دولة إرتريا", "ሃገረ ኤርትራ"],
    "Estonia": ["Eesti", "Republic of Estonia", "Eesti Vabariik"],
    "Eswatini": ["Swaziland", "eSwatini", "Kingdom of Eswatini", "Umbuso weSwatini"],
    "Ethiopia": ["ኢትዮጵያ", "Federal Democratic Republic of Ethiopia", "የኢትዮጵያ ፌዴራላዊ ዴሞክራሲያዊ ሪፐብሊክ"],
    "Fiji": ["Viti", "फ़िजी", "Republic of Fiji", "Matanitu Ko Viti", "फ़िजी गणराज्य"],
    "Finland": ["Suomi", "Republic of Finland", "Suomen tasavalta", "Republiken Finland"],
    "France": ["République française", "French Republic"],
    "Gabon": ["République Gabonaise", "Gabonese Republic"],
    "Gambia": ["The Gambia", "Republic of The Gambia"],
    "Georgia": ["საქართველო", "Sakartvelo"],
    "Germany": ["Deutschland", "Bundesrepublik Deutschland", "Federal Republic of Germany"],
    "Ghana": ["Republic of Ghana"],
    "Greece": ["Ελλάδα", "Elláda", "Hellenic Republic", "Ελληνική Δημοκρατία"],
    "Grenada": [],
    "Guatemala": ["República de Guatemala", "Republic of Guatemala"],
    "Guinea": ["Guinée", "République de Guinée", "Republic of Guinea"],
    "Guinea-Bissau": ["República da Guiné-Bissau", "Republic of Guinea-Bissau"],
    "Guyana": ["Co-operative Republic of Guyana"],
    "Haiti": ["Haïti", "Ayiti", "République d'Haïti", "Repiblik d Ayiti", "Republic of Haiti"],
    "Honduras": ["República de Honduras", "Republic of Honduras"],
    "Hungary": ["Magyarország", "Hungary"],
    "Iceland": ["Ísland", "Lýðveldið Ísland", "Republic of Iceland"],
    "India": ["Bhārat", "भारत", "Republic of India", "भारत गणराज्य", "Bhārat Gaṇarājya"],
    "Indonesia": ["Republik Indonesia", "Republic of Indonesia"],
    "Iran": ["ایران", "Islamic Republic of Iran", "جمهوری اسلامی ایران", "Jomhuri-ye Eslāmi-ye Irān"],
    "Iraq": ["العراق", "Al-'Iraq", "Republic of Iraq", "جمهورية العراق", "Jumhūriīyet al-'Irāq"],
    "Ireland": ["Éire", "Republic of Ireland", "Poblacht na hÉireann"],
    "Israel": ["ישראל", "Yisra'el", "מדינת ישראל", "Medinat Yisra'el", "State of Israel", "دولة إسرائيل", "Dawlat Isrā'īl"],
    "Italy": ["Italia", "Italian Republic", "Repubblica Italiana"],
    "Jamaica": [],
    "Japan": ["日本", "Nihon", "Nippon", "State of Japan", "日本国", "Nihon-koku", "Nippon-koku"],
    "Jordan": ["الأردن", "Al-'Urdun", "Hashemite Kingdom of Jordan", "المملكة الأردنية الهاشمية", "Al-Mamlakah al-'Urdunniyyah al-Hāshimiyyah"],
    "Kazakhstan": ["Қазақстан", "Qazaqstan", "Republic of Kazakhstan", "Қазақстан Республикасы", "Qazaqstan Respublikasy"],
    "Kenya": ["Republic of Kenya", "Jamhuri ya Kenya"],
    "Kiribati": ["Republic of Kiribati", "Ribaberiki Kiribati"],
    "Korea, North": ["North Korea", "조선민주주의인민공화국", "Democratic People's Republic of Korea", "Chosŏn Minjujuŭi Inmin Konghwaguk"],
    "Korea, South": ["South Korea", "대한민국", "Republic of Korea", "Daehan Minguk"],
    "Kosovo": ["Kosova", "Косово", "Republic of Kosovo", "Republika e Kosovës", "Република Косово"],
    "Kuwait": ["الكويت", "State of Kuwait", "دولة الكويت", "Dawlat al-Kuwait"],
    "Kyrgyzstan": ["Кыргызстан", "Kyrgyz Republic", "Кыргыз Республикасы", "Kyrgyz Respublikasy"],
    "Laos": ["ລາວ", "Lao", "Lao People's Democratic Republic", "ສາທາລະນະລັດ ປະຊາທິປະໄຕ ປະຊາຊົນລາວ"],
    "Latvia": ["Latvija", "Republic of Latvia", "Latvijas Republika"],
    "Lebanon": ["لبنان", "Lubnān", "Lebanese Republic", "الجمهورية اللبنانية", "Al-Jumhūrīyah al-Lubnānīyah"],
    "Lesotho": ["Kingdom of Lesotho", "Muso oa Lesotho"],
    "Liberia": ["Republic of Liberia"],
    "Libya": ["ليبيا", "State of Libya", "دولة ليبيا", "Dawlat Libya"],
    "Liechtenstein": ["Principality of Liechtenstein", "Fürstentum Liechtenstein"],
    "Lithuania": ["Lietuva", "Republic of Lithuania", "Lietuvos Respublika"],
    "Luxembourg": ["Luxemburg", "Lëtzebuerg", "Grand Duchy of Luxembourg", "Grand-Duché de Luxembourg", "Großherzogtum Luxemburg", "Groussherzogtum Lëtzebuerg"],
    "Madagascar": ["Madagasikara", "Republic of Madagascar", "Repoblikan'i Madagasikara", "République de Madagascar"],
    "Malawi": ["Republic of Malawi", "Dziko la Malaŵi"],
    "Malaysia": ["مليسيا"],
    "Maldives": ["ދިވެހިރާއްޖެ", "Dhivehi Raajje", "Republic of Maldives", "ދިވެހިރާއްޖޭގެ ޖުމްހޫރިއްޔާ", "Dhivehi Raajjeyge Jumhooriyyaa"],
    "Mali": ["République du Mali", "Republic of Mali"],
    "Malta": ["Repubblika ta' Malta", "Republic of Malta"],
    "Marshall Islands": ["Aolepān Aorōkin M̧ajeļ", "Republic of the Marshall Islands", "Aolepān Aorōkin M̧ajeļ"],
    "Mauritania": ["موريتانيا", "Mūrītānyā", "Islamic Republic of Mauritania", "الجمهورية الإسلامية الموريتانية", "Al-Jumhūrīyah al-Islāmīyah al-Mūrītānīyah"],
    "Mauritius": ["Maurice", "Moris", "Republic of Mauritius", "République de Maurice", "Repiblik Moris"],
    "Mexico": ["México", "United Mexican States", "Estados Unidos Mexicanos"],
    "Micronesia": ["Federated States of Micronesia", "FSM"],
    "Moldova": ["Republic of Moldova", "Republica Moldova"],
    "Monaco": ["Principality of Monaco", "Principauté de Monaco"],
    "Mongolia": ["Монгол улс", "Mongol Uls"],
    "Montenegro": ["Црна Гора", "Crna Gora"],
    "Morocco": ["المغرب", "Al-Maġrib", "Kingdom of Morocco", "المملكة المغربية", "Al-Mamlakah al-Maġribiyah"],
    "Mozambique": ["Moçambique", "Republic of Mozambique", "República de Moçambique"],
    "Myanmar": ["Burma", "မြန်မာ", "Myanma", "Republic of the Union of Myanmar", "ပြည်ထောင်စု သမ္မတ မြန်မာနိုင်ငံတော်"],
    "Namibia": ["Republic of Namibia", "Republiek van Namibië", "Republik Namibia"],
    "Nauru": ["Republic of Nauru", "Repubrikin Naoero"],
    "Nepal": ["नेपाल", "Federal Democratic Republic of Nepal", "संघीय लोकतान्त्रिक गणतन्त्र नेपाल"],
    "Netherlands": ["Nederland", "Holland", "Kingdom of the Netherlands", "Koninkrijk der Nederlanden"],
    "New Zealand": ["Aotearoa", "NZ"],
    "Nicaragua": ["República de Nicaragua", "Republic of Nicaragua"],
    "Niger": ["République du Niger", "Republic of Niger"],
    "Nigeria": ["Federal Republic of Nigeria", "Jamhuriyar Taraiyar Nijeriya"],
    "North Macedonia": ["Северна Македонија", "Severna Makedonija", "Republic of North Macedonia", "Република Северна Македонија", "Republika Severna Makedonija"],
    "Norway": ["Norge", "Noreg", "Kingdom of Norway", "Kongeriket Norge", "Kongeriket Noreg"],
    "Oman": ["عمان", "Sultanate of Oman", "سلطنة عمان", "Salṭanat ʻUmān"],
    "Pakistan": ["پاکستان", "Islamic Republic of Pakistan", "اسلامی جمہوریہ پاکستان", "Islāmī Jumhūriyah Pākistān"],
    "Palau": ["Belau", "Republic of Palau", "Beluu er a Belau"],
    "Panama": ["República de Panamá", "Republic of Panama"],
    "Papua New Guinea": ["Papua Niugini", "Independent State of Papua New Guinea", "Independen Stet bilong Papua Niugini"],
    "Paraguay": ["República del Paraguay", "Tetã Paraguái", "Republic of Paraguay"],
    "Peru": ["Perú", "Republic of Peru", "República del Perú"],
    "Philippines": ["Pilipinas", "Republic of the Philippines", "Republika ng Pilipinas"],
    "Poland": ["Polska", "Republic of Poland", "Rzeczpospolita Polska"],
    "Portugal": ["Portuguese Republic", "República Portuguesa"],
    "Qatar": ["قطر", "State of Qatar", "دولة قطر", "Dawlat Qatar"],
    "Romania": ["România"],
    "Russia": ["Россия", "Rossiya", "Russian Federation", "Российская Федерация", "Rossiyskaya Federatsiya"],
    "Rwanda": ["Republic of Rwanda", "République du Rwanda", "Repubulika y'u Rwanda"],
    "Saint Kitts and Nevis": ["Federation of Saint Christopher and Nevis"],
    "Saint Lucia": [],
    "Saint Vincent and the Grenadines": [],
    "Samoa": ["Independent State of Samoa", "Malo Saʻoloto Tutoʻatasi o Sāmoa"],
    "San Marino": ["Republic of San Marino", "Repubblica di San Marino"],
    "São Tomé and Príncipe": ["Democratic Republic of São Tomé and Príncipe", "República Democrática de São Tomé e Príncipe"],
    "Saudi Arabia": ["السعودية", "Al-Saʿūdīyah", "Kingdom of Saudi Arabia", "المملكة العربية السعودية", "Al-Mamlakah al-ʿArabīyah as-Saʿūdīyah"],
    "Senegal": ["République du Sénégal", "Republic of Senegal"],
    "Serbia": ["Србија", "Srbija", "Republic of Serbia", "Република Србија", "Republika Srbija"],
    "Seychelles": ["Republic of Seychelles", "République des Seychelles", "Repiblik Sesel"],
    "Sierra Leone": ["Republic of Sierra Leone"],
    "Singapore": ["Singapura", "சிங்கப்பூர்", "新加坡", "Republic of Singapore", "Republik Singapura", "சிங்கப்பூர் குடியரசு", "新加坡共和国"],
    "Slovakia": ["Slovensko", "Slovak Republic", "Slovenská republika"],
    "Slovenia": ["Slovenija", "Republic of Slovenia", "Republika Slovenija"],
    "Solomon Islands": [],
    "Somalia": ["الصومال", "Soomaaliya", "Federal Republic of Somalia", "جمهورية الصومال الفيدرالية", "Jamhuuriyadda Federaalka Soomaaliya"],
    "South Africa": ["Suid-Afrika", "iNingizimu Afrika", "iSewula Afrika", "Republic of South Africa", "Republiek van Suid-Afrika"],
    "South Sudan": ["Republic of South Sudan", "جمهورية جنوب السودان"],
    "Spain": ["España", "Kingdom of Spain", "Reino de España"],
    "Sri Lanka": ["ශ්‍රී ලංකා", "இலங்கை", "Democratic Socialist Republic of Sri Lanka", "ශ්‍රී ලංකා ප්‍රජාතාන්ත්‍රික සමාජවාදී ජනරජය", "இலங்கை சனநாயக சோசலிசக் குடியரசு"],
    "Sudan": ["السودان", "As-Sudan", "Republic of the Sudan", "جمهورية السودان", "Jumhūrīyat as-Sūdān"],
    "Suriname": ["Republic of Suriname", "Republiek Suriname"],
    "Sweden": ["Sverige", "Kingdom of Sweden", "Konungariket Sverige"],
    "Switzerland": ["Schweiz", "Suisse", "Svizzera", "Svizra", "Swiss Confederation", "Schweizerische Eidgenossenschaft", "Confédération suisse", "Confederazione Svizzera", "Confederaziun svizra"],
    "Syria": ["سوريا", "Sūriyā", "Syrian Arab Republic", "الجمهورية العربية السورية", "Al-Jumhūrīyah al-ʻArabīyah as-Sūrīyah"],
    "Tajikistan": ["Тоҷикистон", "Tojikiston", "Republic of Tajikistan", "Ҷумҳурии Тоҷикистон", "Jumhurii Tojikiston"],
    "Tanzania": ["United Republic of Tanzania", "Jamhuri ya Muungano wa Tanzania"],
    "Thailand": ["ประเทศไทย", "Prathet Thai", "Kingdom of Thailand", "ราชอาณาจักรไทย", "Ratcha-anachak Thai"],
    "Timor-Leste": ["East Timor", "Timór Lorosa'e", "Democratic Republic of Timor-Leste", "República Democrática de Timor-Leste"],
    "Togo": ["Togolese Republic", "République togolaise"],
    "Tonga": ["Kingdom of Tonga", "Puleʻanga Fakatuʻi ʻo Tonga"],
    "Trinidad and Tobago": ["Republic of Trinidad and Tobago"],
    "Tunisia": ["تونس", "Tūnis", "Tunisie", "Republic of Tunisia", "الجمهورية التونسية", "Al-Jumhūrīyah at-Tūnisīyah", "République tunisienne"],
    "Türkiye": ["Turkey", "Türkiye Cumhuriyeti", "Republic of Türkiye"],
    "Turkmenistan": ["Türkmenistan"],
    "Tuvalu": [],
    "Uganda": ["Republic of Uganda", "Jamhuri ya Uganda"],
    "Ukraine": ["Україна", "Ukrayina"],
    "United Arab Emirates": ["الإمارات العربية المتحدة", "Al-ʾImārāt Al-ʿArabīyah Al-Muttaḥidah", "UAE", "UAE"],
    "United Kingdom": ["UK", "Great Britain", "Britain", "United Kingdom of Great Britain and Northern Ireland"],
    "United States": ["United States of America", "USA", "US", "America"],
    "Uruguay": ["República Oriental del Uruguay", "Oriental Republic of Uruguay"],
    "Uzbekistan": ["O'zbekiston", "Ўзбекистон", "Republic of Uzbekistan", "O'zbekiston Respublikasi", "Ўзбекистон Республикаси"],
    "Vanuatu": ["Republic of Vanuatu", "Ripablik blong Vanuatu", "République de Vanuatu"],
    "Vatican City": ["Holy See", "Vatican", "Stato della Città del Vaticano", "Status Civitatis Vaticanae"],
    "Venezuela": ["Bolivarian Republic of Venezuela", "República Bolivariana de Venezuela"],
    "Vietnam": ["Việt Nam", "Socialist Republic of Vietnam", "Cộng hòa Xã hội chủ nghĩa Việt Nam"],
    "Yemen": ["اليمن", "Al-Yaman", "Republic of Yemen", "الجمهورية اليمنية", "Al-Jumhūrīyah Al-Yamanīyah"],
    "Zambia": ["Republic of Zambia"],
    "Zimbabwe": ["Republic of Zimbabwe"]
}